
services:
  - type: web
    name: central-de-atendimento
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: BACKEND_PUBLIC_URL
        sync: false
      - key: N8N_WEBHOOK_URL
        sync: false
      - key: ACCOUNT_ID
        sync: false
      - key: API_ACCESS_TOKEN
        sync: false
