services:
  - type: web
    name: central-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: BACKEND_PUBLIC_URL
        value: https://central-de-atendimento.onrender.com
      - key: ACCOUNT_ID
        value: "2"
      - key: API_ACCESS_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: N8N_WEBHOOK_URL
        value: https://n8n.srv847937.hstgr.cloud/webhook/enviar-campanha

  - type: web
    name: central-frontend
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://central-de-atendimento.onrender.com
